#!/bin/bash
#
#SBATCH --job-name=RNA_QC
#SBATCH --ntasks=1 # Number of cores/threads
#SBATCH --mem=2000 # Ram in Mb
#SBATCH --partition=production 
#SBATCH --time=0-00:30:00

##########################################################################################
# Author: AJ Mendiola
# Email: apmendiola@ucdavis.edu
##########################################################################################

###################
# Run Information #
###################

start=`date +%s`

hostname

################
# Load Modules #
################

module load multiqc/1.10.1

###########
# MultiQC #
###########

call="multiqc
. \
--ignore alignLogs/ \
--ignore raw_sequences/ \
--ignore chr10/ "

echo $call
eval $call

########
# Copy #
########

mkdir GeneCounts
"$(find `.` -name '*ReadsPerGene.out.tab' -print0 | xargs -0 cp -t GeneCounts)"

###################
# Run Information #
###################

end=`date +%s`
runtime=$((end-start))
echo $runtime

call="STAR \
--runThreadN 60 \
--runMode genomeGenerate \
--genomeDir star_50/ \
--genomeFastaFiles assemblies/papAnu4.fa \
--sjdbGTFfile assemblies/papAnu4.ncbiRefSeq.gtf \
--sjdbOverhang 50
--limitGenomeGenerateRAM 100000000000"